include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: true
    unawaited_futures: true
    use_build_context_synchronously: false
    avoid_redundant_argument_values: true
    unnecessary_lambdas: true
