name: Feature request
description: Suggest an idea for this project
title: "[feat] "
labels: ["type:feature"]
body:
  - type: textarea
    attributes:
      label: Problem
      description: What problem are you trying to solve?
  - type: textarea
    attributes:
      label: Proposal
      description: A clear and concise description of what you want to happen
