name: flutter-ci

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - name: Install dependencies
        run: |
          cd frontend
          flutter pub get
      - name: Analyze
        run: |
          cd frontend
          flutter analyze
      - name: Test
        run: |
          cd frontend
          flutter test

  coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - name: Install dependencies
        run: |
          cd frontend
          flutter pub get
      - name: Run tests with coverage
        run: |
          cd frontend
          flutter test --coverage
      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: frontend/coverage/lcov.info
          flags: unittests
          fail_ci_if_error: true
