name: build-and-deploy

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install dependencies
        run: |
          cd frontend
          flutter pub get
      - name: Analyze
        run: |
          cd frontend
          flutter analyze
      - name: Test
        run: |
          cd frontend
          flutter test

  build-web:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Build Web (with correct base href)
        run: |
          cd frontend
          flutter pub get
          flutter build web --release --base-href /habit-tracker/
          # SPA-404 Fix: kopiere index.html -> 404.html
          cp build/web/index.html build/web/404.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/build/web
          publish_branch: gh-pages

  build-android:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Build Android APK
        run: |
          cd frontend
          flutter pub get
          flutter build apk --release
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: frontend/build/app/outputs/flutter-apk/app-release.apk

  build-ios:
    needs: test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Build iOS (no codesign)
        run: |
          cd frontend
          flutter pub get
          flutter build ios --release --no-codesign
      - name: Upload iOS build
        uses: actions/upload-artifact@v4
        with:
          name: ios-release
          path: frontend/build/ios/iphoneos
