name: release-ios

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods

      - name: Install dependencies
        run: |
          cd frontend
          flutter pub get

      - name: Build iOS (no codesign)
        run: |
          cd frontend
          flutter build ios --release --no-codesign

      - name: Zip iOS build
        run: |
          cd frontend/build/ios/iphoneos
          zip -r ios-release.zip Runner.app

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: frontend/build/ios/iphoneos/ios-release.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
